### ISSUE TITLE
 How can I get apns4erl integrated with ejabberd 

### ISSUE THREAD

**Issue by joanlopez** [inaka/apns4erl#100]
Indeed I've seen that there's another closed issue with the same name, but there's no any guide/tutorial that explains how to make this integration.

I don't know some things:
1. Where I have to put the dependency (maybe on rebar.config.script)?
2. Where I have to put the configuration?
3. Where I have to make the connection?

And some other things..

Someone can helps me?

Thanks!

**Comment by manuel-rubio** [comment]
well, ejabberd as external module is a bit comple but if you modify the current code, you can add the dependency in rebar.config file, it should do the magic :-) ... after that, you'll need to create a module to use it, of course.

**Comment by joanlopez** [comment]
Okay, I will add the 'apns4erl' as a dependency in my rebar.config. 
This theorically solves my first question..
But what about the other things?
I'm implementing a module with a hook and so on.. but for example:

- Where I should define the configurations detailed on apns4erl readme?
(Maybe on the rebar.config also?)

- Where I should create the connection? 
(Maybe on the module init function? Or every time that I send a push?)

Etc..

Many thanks @manuel-rubio !!! :+1:

**Comment by manuel-rubio** [comment]
About the questions:

* you should to define the configuration in the start of the new module you have to create.
* the same, in the start of the module.

About configuration, for example, you can add it to the module configuration to get it in the `Opts` param for start the module. It's not hard to do, but you need to review code from other modules to realize how to do it ;-)

If you need more help we can talk in DM, talk in spanish is better for me :-P

**Comment by joanlopez** [comment]
Okay, It will be better.

DMs in spanish, but with which communication channel? jajaja

Then I will write a Wiki page/tutorial like @monkeyfdude but explaining all the integration process.

**Comment by ferigis** [comment]
I think we can close that ticket
