### ISSUE TITLE
rustyio/sync in rebar.config why?

### ISSUE THREAD

**Issue by cystbear** [inaka/apns4erl#106]
Hey guys, I am trying to integrate `apns4erl` with my Erlang application. 
Is any reason to have [rustyio/sync](https://github.com/rustyio/sync) in rebar.config?, looks like it's for dev purposes only, isn't it?

**Comment by elbrujohalcon** [comment]
Just for dev purposes, feel free to send a PR to move it to `SHELL_DEPS` or just plainly remove it.

**Comment by cystbear** [comment]
Done https://github.com/inaka/apns4erl/pull/107
