### ISSUE TITLE
`apns_queue` module question

### ISSUE THREAD

**Issue by cystbear** [inaka/apns4erl#108]
**What is purposes of `apns_queue` module usage?**

As far as I got we store push messages inside of queue just before send message itself, for sure, to handle case when connection to apple's server is unstable, or closed at the moment.
Also `apns_queue` serves e to resend failed push messages.
But we do not remove successfully sent push message from that queue, and new messages just displace prev one.

Should I remove messages from queue by myself? Looks like no, cause there is no any interface funs to do this.

**Comment by elbrujohalcon** [comment]
@manuel-rubio this one is for you, and, in the process of checking @cystbear's comment, I also found a typo [here](https://github.com/inaka/apns4erl/blob/master/src/apns_queue.erl#L77)

**Comment by elbrujohalcon** [comment]
@cystbear for what I gather, correctly-sent messages are removed when a message fails (i.e. [here](https://github.com/inaka/apns4erl/blob/master/src/apns_queue.erl#L118))

**Comment by cystbear** [comment]
@elbrujohalcon about typo, you mean `queue:liat/1` name looks correct it's not a fat fingers list -> liat :)

**Comment by cystbear** [comment]
@elbrujohalcon so queue will be cleared at first fail message or disconnect, am I right?

**Comment by manuel-rubio** [comment]
@cystbear the queue stores all the message which are send to APNS. The bad news is APNS doesn't give us feedback if the message was ok, and even the errors could arrive a bit later so, we have to create a _queue_ to store all the messages and if we don't receive anything in specific time, then we can remove those messages... but if you receive an error, then we have to get that ID, search in that queue and suppose the messages previous to that are ok, and the rest should be resent.

**Comment by cystbear** [comment]
@manuel-rubio finally got the logic, thanks. But can we use Apple's feedback feature to improve resend functionality? Kinda when Apple sent feedback to us that some message failed, then ask connection/queue resend it.

For this we need to a bit open API of connection and its queue, to allow manipulate with queue entries. Something like that. 

Sorry I reviewed `apns4erl` only few minutes, and can miss something. Anyway demo PushNotifications works like a charm, just trying to understand better lib before deeply integrate it to my Erlang application.

**Comment by manuel-rubio** [comment]
@cystbear well, you can implement your own logic using the callbacks for errors. In my case, I prefer to lose that message because it's possible the message is wrong and I don't want Apple ban me ;-)

**Comment by cystbear** [comment]
@elbrujohalcon @manuel-rubio thanks guys
