### ISSUE TITLE
Does  this project  support   apns ‘s HTTP/2 connection ?

### ISSUE THREAD

**Issue by zhaohansprt** [inaka/apns4erl#122]
support  Apple APNs HTTP/2 connection

**Comment by elbrujohalcon** [comment]
No, it doesn't.

**Comment by zhaohansprt** [comment]
have a upgrade roadmap for this?

**Comment by ferigis** [comment]
Hi @zhaohansprt , actually we are currently working on apns4erl v2 which will include the http2 suport. We hope finish it soon. Stay tuned!

**Comment by ferigis** [comment]
Hi @zhaohansprt , currently we are supporting the new APNs API over HTTP2. we would appreciate feedback if you use it :)

**Comment by zhaohansprt** [comment]
dude you guys are awesome!!
