### ISSUE TITLE
Erlang/OTP 18?

### ISSUE THREAD

**Issue by cwmaguire** [inaka/apns4erl#164]
apn4serl compiles under Erlang/OTP 18.2 with a minor changes (as of 25ad9d23a372). Is there anything else (e.g. ssl) that specifically requires Erlang/OTP 19+? I've got everything coded up for Erlang/OTP 18.2 (large project, hard to upgrade) but I can't connect to the APNS server: I just keep getting a timeout. Before I go any further I'd like to know if our Erlang version is maybe the issue. (I can connect with openssl s_client, but not with apns4erl).

**Comment by ferigis** [comment]
Hi @cwmaguire, I didn't test apns4erl with Erlang 18. If you did the hack and it compiles well I would think your issue could be related with openssl since it needs TLS 1.2+. Even if you connected with s_client, did you try to send something to APNs? Did you get a response from it?

**Comment by cwmaguire** [comment]
We have openssl 1.0.2j. I tried doing "GET https://www.howsmyssl.com/a/check HTTP/1.1" and it reported that GET was using TLS 1.2. I haven't tried sending anything with SSL yet. I'll look up how to do that and see if I can successfully send something. Thanks for the tip.

**Comment by cwmaguire** [comment]
Okay, I can send a push with curl using a certificate and I get BadDeviceToken, so that's a start! 

I'll dig through the SSL traces and see what I can come up with. Thanks for the help.

**Comment by cwmaguire** [comment]
I picked up these SSL options from [here](https://github.com/SilentCircle/apns_erlv3/blob/master/src/apns_erlv3_session.erl) and I was able to connect.
{honor_cipher_order, false},
{versions, ['tlsv1.2']},
{alpn_preferred_protocols, [<<"h2">>]}

**Comment by monkeyfdude** [comment]
@cwmaguire where did you these options. I am getting this error https://github.com/inaka/apns4erl/issues/118

Please help me resolve this.

**Comment by cwmaguire** [comment]
@monkeyfdude 

> where did you these options?

I added these options to the TransportOpts list in apns_connection:open_gun_connection/1.
```erlang
  TransportOpts = case type(Connection) of
  cert ->
    Certfile = certfile(Connection),
    Keyfile = keyfile(Connection),
    [{certfile,Certfile},
     {keyfile,Keyfile},
     {honor_cipher_order, false},
     {versions, ['tlsv1.2']},
     {alpn_preferred_protocols, [<<"h2">>]}];
```

**Comment by cwmaguire** [comment]
@monkeyfdude Note that we're using the new APNS HTTP/2 API. I see from #118 that you're accessing the "legacy" binary SSL API at gateway.sandbox.push.apple.com whereas I'm using api.development.push.apple.com:443 which is the HTTP/2 API.

**Comment by monkeyfdude** [comment]
Can you please suggest a solution for #118 ?

**Comment by monkeyfdude** [comment]
@cwmaguire did you build apns4erl v2 using erlang 19 and running it on erlang 18?

rebar3/apns4erl does not compile with erlang < 19.

If you built using erlang 18, can you please describe the steps you did?

**Comment by monkeyfdude** [comment]
I am getting this error even with TransportOpts changes.

Can you help me resolve this please?

```
2017-05-05 11:32:14.958 [error] <0.472.0> SSL: cipher: ssl_alert.erl:93:Fatal error: internal error
2017-05-05 11:32:20.009 [error] <0.483.0> SSL: cipher: ssl_alert.erl:93:Fatal error: internal error
2017-05-05 11:32:24.761 [error] <0.470.0> gen_server 'my-apns-connection' terminated with reason: timeout
2017-05-05 11:32:24.761 [error] <0.470.0> CRASH REPORT Process 'my-apns-connection' with 0 neighbours exited with reason: timeout in gen_server:terminate/7 line 826
```

**Comment by ferigis** [comment]
Hi @monkeyfdude, since you are trying to update your apns4erl to v2, I recommend you to make some tests first. I mean, download the apns4erl code and play with the console until you achieve push something to APNS and forwarding the messages to your devices. Once you achieve this that implies your certificate and headers are correct, then you can to try to update the library in your ejabberd server.

**Comment by monkeyfdude** [comment]
Thanks. I will try that.

The ssl_alert error is gone. But I am getting the timeout now.

**gen_server 'my-apns-connection' terminated with reason: timeout**

**Comment by monkeyfdude** [comment]
I get timeout with following changes:

test.config:

```
[
 {
   apns,
   [ {apple_host,       "api.development.push.apple.com"}
   , {apple_port,       443}
   , {certfile,         "/etc/ejabberd/certs/apns-dev-cert.pem"}
   , {keyfile,          "/etc/ejabberd/certs/apns-dev-key-noenc.pem"}
   , {token_keyfile,    "priv/APNsAuthKey_KEYID12345.p8"}
   , {timeout,          10000}

   %% APNs Headers

   , {apns_id,          undefined}
   , {apns_expiration,  0}
   , {apns_priority,    10}
   , {apns_topic,       "com.example.myapp"}
   , {apns_collapse_id, undefined}

   %% Feedback
   , {feedback_host,    "feedback.push.apple.com"}
   , {feedback_port,    2195}
   ]
 },
 {sasl, [{sasl_error_logger, false}]}
].
```

```
erl -pa _build/default/lib/*/ebin -config test/test.config
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.2.1  (abort with ^G)
1> apns:start().
ok
2> apns:connect(cert, my_first_connection).

=ERROR REPORT==== 5-May-2017::12:00:29 ===
** Generic server my_first_connection terminating 
** Last message in was timeout
** When Server state == #{backoff => 1,
                          backoff_ceiling => 10,
                          client => <0.34.0>,
                          connection => #{apple_host => "api.development.push.apple.com",
                            apple_port => 443,
                            certfile => "/etc/ejabberd/certs/apns-dev-cert.pem",
                            keyfile => "/etc/ejabberd/certs/apns-dev-key-noenc.pem",
                            name => my_first_connection,
                            type => cert},
                          gun_connection => <0.64.0>}
** Reason for termination == 
** timeout
{error,timeout}
3> 
```
Code changes:

```
  TransportOpts = case type(Connection) of
    cert ->
      Certfile = certfile(Connection),
      Keyfile = keyfile(Connection),
      [{certfile,Certfile},
      {keyfile,Keyfile},
      {honor_cipher_order, false},
      {versions, ['tlsv1.2']},
      {alpn_preferred_protocols, [<<"h2">>]}];
    token ->
      []
  end,
```

**Comment by ferigis** [comment]
you have to change the data regarding your app. This is not correct
```
, {apns_id,          undefined}
   , {apns_expiration,  0}
   , {apns_priority,    10}
   , {apns_topic,       "com.example.myapp"}
   , {apns_collapse_id, undefined}
```

**Comment by monkeyfdude** [comment]
I did change that. It did not work. 

But I am not event able to connect from apns:connect()

**Comment by ferigis** [comment]
did you try to push something without apns4erl? are you sure your certs and http2 headers are correct?

**Comment by monkeyfdude** [comment]
@cwmaguire You may be right. Let me investigate.

Please keep an eye on this issue. I will keep updating as I investigate.

**Comment by monkeyfdude** [comment]
I was able to connect & send atleast 1 notification successfully. Thanks for all your help.

I have other issues. I am opening a new issue.
