### ISSUE TITLE
where do I register feedback handlers in v2?

### ISSUE THREAD

**Issue by monkeyfdude** [inaka/apns4erl#166]
In v1, I did this to get feedback inside  ejabberd module
```
        {ok, _} = apns:connect(my_conn, 
                              fun ?MODULE:handle_apns_error/2, 
                              fun ?MODULE:handle_apns_delete_subscription/1),

handle_apns_error(MsgId, Status) ->
  ?ERROR_MSG("Error on msg ~p: ~p~n", [MsgId, Status]).

handle_apns_delete_subscription({ExpiredAt,TokenStr}) ->
    ?WARNING_MSG("Device with token ~p removed the app at ~p~n", [TokenStr, ExpiredAt]),
```
What do I need to do in apns4erl v2 to get the feedback (handle_apns_delete_subscription)?

**Comment by ferigis** [comment]
from README file:

## Feedback

`apns4erl` also allows us to get feedback from APNs service. It does it thru the [binary API](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/BinaryProviderAPI.html).

In order to get feedback we would need a `Provider Certificate` and have it set at `config` file as we do for `push notifications`. Then we will call `apns:get_feedback/0`. The response will be a list of `feedback()`

```erlang
-type feedback() :: {calendar:datetime(), string()}.
```
Where the first element in the tuple is the date when the device uninstalled the app and the second element is the Device Id.

**Comment by monkeyfdude** [comment]
I read that but was unable to understand where do I register the callback like I did in v1.

Please pardon my ignorance. Can you please provide a code snippet like I have above for v1

**Comment by ferigis** [comment]
Hi @monkeyfdude, no worries, this is not ignorance :)
Apns v2 is completely different than V1, so don't try to do the same.
In V1 the feedback was an asynchronous callback. Now it is synchronous, we have to ask when we want to get the feedback.
Actually we are using old binary API for feedback because it was nothing implemented in the new HTTP2 APNS API

**Comment by ferigis** [comment]
this new V2 was developed following https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html
were there was nothing about feedback. For this reason we have to use the old binary API in synchronous mode

**Comment by monkeyfdude** [comment]
I am so sorry. What do I need to do inside my ejabberd module to get feedback? 

* The ejabberd module runs a gen_server.
* I start apns4erl app ```apns:start()```
* It opens apns_connection and keeps running

When will I get the feedback in my ejabberd module?

**Comment by elbrujohalcon** [comment]
@monkeyfdude you have to decide that yourself. `apns4erl` v2 gives you a function to get the feedback (`apns:get_feedback()`). You'll have to periodically call it yourself if you want to periodically check for feedback.

**Comment by monkeyfdude** [comment]
Isn't that a change from v1?

In v1, every timeout second, feedback connection will be made and the handle was called?

**Comment by elbrujohalcon** [comment]
@monkeyfdude it's indeed a change. And we changed because we were misusing Apple's feedback mechanism. We were treating it as a permanent connection, when in fact it is not.

**Comment by monkeyfdude** [comment]
Thank you :(

**Comment by ferigis** [comment]
@monkeyfdude feedback is not a feature in the new APNs API. We tried to keep it with the old binary API.
I am not an expert in ejabberd but regarding the new http2 codes (you can check them [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1)) you can see a '410 The device token is no longer active for the topic.', maybe that is the reason why Apple doesn't implement feedback in this new API. If you check the response codes you can include your "feedback" logic when you get that 410, this is only a suggestion

**Comment by monkeyfdude** [comment]
Please answer 1 more question. Can I have 2 gen_servers running 2 apns4erl app. For eg.

gen_server 1 - used for sending messages
```
init([Host, Opts]) -> 
        apns:start(), 
        {ok, _} = apns:connect(..),
```

gen_server 2 - used for periodic feedback
```
init([Host, Opts]) -> 
        apns:start(),
```

**Comment by elbrujohalcon** [comment]
@monkeyfdude you can, but you don't need to start apns twice.
I would not even put the `apns:start()` code there, to be honest.
But even if you need to, then do it just once.

**Comment by monkeyfdude** [comment]
Thank you. Please keep this open in case I have more questions. I don't know erlang.

**Comment by monkeyfdude** [comment]
what will happen if I call following twice in a row:

```apns:connect(cert, ConnectionName)```

In v1, I was getting ```{error, already_started}```
