### ISSUE TITLE
Erlang Crashing

### ISSUE THREAD

**Issue by monkeyfdude** [inaka/apns4erl#168]
I am trying to run apns4erl v2 inside ejabberd otp 18 but I get crash dump. I have attached the dump file.

Would you be able to tell me what is wrong? I have limited knowledge in Erlang.

**Ubuntu 16.03**
```
erl -v
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V7.2.1  (abort with ^G)
```

**ejabberd code**
```
init([Host, _Opts]) ->
        apns:start(),
        {ok, _} = apns:connect(cert, ?APNS_CONNECTION),
        {ok, #state{host = Host}}.
```

**apns4erl v2 built with erlang 18** #164 

```
{application,apns,
             [{description,"APNs provider for Apple Push Notification services (APNs) in Erlang"},
              {vsn,"2.0.0"},
              {id,"apns"},
              {registered,[]},
              {applications,[kernel,stdlib,jsx,gun,base64url]},
              {modules,[apns,apns_app,apns_connection,apns_feedback,apns_os,
                        apns_sup,apns_utils]},
              {mod,{apns_app,[]}},
              {maintainers,["Inaka"]},
              {licenses,["Apache 2.0"]},
              {env, [
                 {apple_host, "api.development.push.apple.com"},
                 {apple_port, 443},
                 {cert_file, "/etc/ejabberd/certs/apns-dev-cert.pem"},
                 {key_file, "priv/apns-dev-key-noenc.pem"},
                 {token_keyfile, undefined},
                 {timeout, 10000}
              ]},
              {links,[{"Github","https://github.com/inaka/apns4erl"}]},
              {build_tools,["rebar3"]}]}.
```
[erl_crash_20170505-103244.txt](https://github.com/inaka/apns4erl/files/978760/erl_crash_20170505-103244.txt)

**Comment by elbrujohalcon** [comment]
@monkeyfdude according to your crashdump slogan, this is the error:

```erlang
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}}
```

You can see that using, for instance, [recon](https://github.com/ferd/recon)'s `erl_crashdump_analyzer.sh`.

The key word there is `nodistribution`. This is certainly not an `apns4erl` error. A quick googling lead me to [this thread](https://www.ejabberd.im/node/872) where you can see people fighting against that same error in ejabberd-land.

If I were you, I would ask there.

**Comment by monkeyfdude** [comment]
@elbrujohalcon Thank you so much.

But the crash happens only when put apns v2 built with erlang 18 modules inside ejabberd.

Could there be some apns4erl dependency that is not found with erlang 18??

**Comment by elbrujohalcon** [comment]
I really doubt apns would cause this, specially considering that not even the application manager is started when the VM crashes.
Using the same tool I showed you above, you can see that only 5 processes were started in the node. The last one was most likely going to be the application_master, but it died and the whole VM crashed.
May your problem be related to processone/ejabberd#1158 ?
Are you trying to use `ejabberdctl` for this?
In any case, I still maintain that this is almost certainly an issue related to how your computer is configured or how you're trying to start ejabberd. It has most likely nothing to do with `apns` at all.

**Comment by monkeyfdude** [comment]
@elbrujohalcon Let me investigate. I will close this.
