### ISSUE TITLE
V2 Need async_push_notification

### ISSUE THREAD

**Issue by boboxiaodd** [inaka/apns4erl#172]
i use v2
i found the push_notification is sync mode, 
Even if you use spawn, sending multiple notifications at the same time can be delayed

**Comment by ferigis** [comment]
Hi @boboxiaodd. Thanks for using our library.
We did it synchronous because every HTTP2 request to APNs servers has a response. Did you try opening many connections and balancing the requests between them?

**Comment by boboxiaodd** [comment]
Thank you! i try to make a pool connections to apns ,and push_notification with random connection.

**Comment by ferigis** [comment]
@boboxiaodd your welcome.
If you are thinking about a pool, maybe you could take a look on [worker_pool](https://github.com/inaka/worker_pool) :)
