### ISSUE TITLE
Base64 newline characters

### ISSUE THREAD

**Issue by dgtony** [inaka/apns4erl#180]
Hi!
There is an issue that I've encountered working with APNs from CentOS 7 box. Some old versions of native utility base64 could limit string length producing newline symbols (`\n`), and It leads to _InvalidProviderToken_ response from APNs.
This problem could be easily fixed with a small change in _generate_token_:

```
-spec generate_token(binary(), binary()) -> token().
generate_token(TeamId, KeyId) ->
  Algorithm = <<"ES256">>,
  Header = jsx:encode([ {alg, Algorithm}
                      , {typ, <<"JWT">>}
                      , {kid, KeyId}
                      ]),
  Payload = jsx:encode([ {iss, TeamId}
                       , {iat, apns_utils:epoch()}
                       ]),
  HeaderEncoded = base64url:encode(Header),
  PayloadEncoded = base64url:encode(Payload),
  DataEncoded = <<HeaderEncoded/binary, $., PayloadEncoded/binary>>,
  Signature = strip_b64(apns_utils:sign(DataEncoded)),
  <<DataEncoded/binary, $., Signature/binary>>.


-spec strip_b64(binary()) -> binary().
strip_b64(BS) ->
  binary:list_to_bin(binary:split(BS, [<<"\n">>, <<"=">>], [global])).

```

**Comment by ferigis** [comment]
Hi @dgtony thanks for your feedback!
After that change you could get a `200` from APNs instead of the _InvalidProviderToken_?
I mean, is your fix tested?
Thanks!

**Comment by dgtony** [comment]
Yes, in my case it has solved the problem.

**Comment by ferigis** [comment]
great, could you create a PR with your fix please?
