### ISSUE TITLE
apns:close_connection don't closed h2_connect

### ISSUE THREAD

**Issue by boboxiaodd** [inaka/apns4erl#209]
https://github.com/inaka/apns4erl/blob/7be3493011ecc43439526338ba5e62ae54fc4737/src/apns_connection.erl#L219
i modify apns_connect.erl and fixed this issues.
```erlang
handle_cast(stop,  #{http2_connection := HTTP2Conn} = State) ->
   h2_client:stop(HTTP2Conn),
   {stop, normal, State};
```
by the way , i use chatterbox 0.7.0 ,and it replace gen_fsm to gen_statem

**Comment by ferigis** [comment]
Hi @boboxiaodd , thanks for the fix. Could you please raise a PR with your fix?

**Comment by boboxiaodd** [comment]
sorry @ferigis i don't know how to do it. 
i use apns:close_connection every 10min ，and use apns:connect a new h2_connect
to solve chatterbox's memory leak
