### ISSUE TITLE
how to send mutiple token to apns in one time?

### ISSUE THREAD

**Issue by Heyaojia** [inaka/apns4erl#223]
as the question,how to send a series of token to apns in one time, wish your answer

**Comment by Heyaojia** [comment]
> Hi @Heyaojia , thanks for using our library :)
> 
> I am not sure if I understand your question, could you elaborate please?
> 
> If you are referring to a supported feature in APNs please send us the link to the official documentation for that and I could take a look and check if we can achieve that with `apns4erl`

thank you for your reply, about the question , i want to send a token list to apns one time,try to wake up those devices, Can apns4erl do that?

**Comment by ferigis** [comment]
if by `token list` you mean sending a list of push notifications in just one request that is not allowed in `apns4erl` :(

**Comment by Heyaojia** [comment]
Thank you for your answer，best regard.
