### ISSUE TITLE
Rebar compile issues when included in other projects

### ISSUE THREAD

**Issue by etxemag75** [inaka/apns4erl#225]
rebar.conf
    {apns,".*", {git, "https://github.com/inaka/apns4erl.git", {branch, master}}},

Pulling apns from {git,"https://github.com/inaka/apns4erl.git",
                       {branch,master}}
Cloning into 'apns'...
Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{code,which,
                                  [{rebar3_codecov,"0.1.0"}],
                                  [{file,"code.erl"},{line,724}]},
                                 {rebar_core,'-plugin_modules/3-lc$^0/1-0-',
                                  1,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,plugin_modules,3,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,244}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,271}]},
                                 {rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,93}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]}]}}
make: *** [Makefile:15: get-deps] Error 1

**Comment by elbrujohalcon** [comment]
Yeah, we don't support old rebar apns4erl in v2.0.
You need to use rebar3.
If you want to use the old rebar, you have to use the old apns4erl: https://github.com/inaka/apns4erl/releases/tag/1.0.6-final

Cheers!
