### ISSUE TITLE
Maintenance-related issues

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/apns4erl#235]
I'm testing this over OTP 19 to 23, so instead of creating several individual issues I'll try to concentrate what I find important in this one.

___1
Q: Is `rebar3_codecov` actively used?
I know the plugin is in `rebar.config` but the associated project seems unmaintained and there's already a compilation warning (not very important).

Targets:
* OTP 19
* OTP 20 (also shows a warning on `export_all`)
* OTP 21 (also shows warning on `erlang:get_stacktrace/0: deprecated`)
* OTP 22
* OTP 23 (also shows a warning on `===> Unable to run post hooks for 'ct', command 'analyze' in namespace 'codecov' not found.`)

**Proposal**: get rid of `rebar3_codecov`. (this also prevents running tests on OTP 19, since it's using yet-undefined `string:split`)

___2
Q: Is there a replacement for `aleppo` we want to adopt?
There's compilation warnings when doing `rebar3 ct`.

Targets:
* OTP 19
* OTP 20
* OTP 21
* OTP 22
* OTP 23

**Proposal**: none, waiting on your feedback.

___3
Q: Is there a replacement for `katana` (0.4.0) we want to adopt?
There's compilation warnings when doing `rebar3 ct`.

Targets:
* OTP 20
* OTP 21 (also shows warning on `erlang:get_stacktrace/0: deprecated`)
* OTP 22
* OTP 23

**Proposal**: none, waiting on your feedback.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, are you a maintainer of this? If not, who could give me some guidance, here?

**Comment by elbrujohalcon** [comment]
I am not. This is @ferigis' project.

**Comment by paulo-ferraz-oliveira** [comment]
OK, I'll wait on @ferigis' feedback, then. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by ferigis** [comment]
hi Paulo, sorry for the late response, I have been quite disconnected lately.

First of all thanks for using apns4erl and helping us with the maintenance :)

Honestly I am not aware of the latest projects in Erlang since I am writing a lot of Elixir these days so I would like to hear @elbrujohalcon opinion.

Brujo, what do you think about the proposals? I am not sure if Aleppo/katana have a proper replacement or maybe we should update it in order to avoid warnings.

**Comment by elbrujohalcon** [comment]
@ferigis @paulo-ferraz-oliveira:

- Get rid of `rebar3_codecov`. Yeah, go ahead, kill it.
- `aleppo`. I have no idea what we are using it for, honestly? Is it because this project uses an old version of `elvis` somewhere?

**Comment by elbrujohalcon** [comment]
I just checked and all those deps are only used for tests!
Yeah… @paulo-ferraz-oliveira @ferigis: You can do whatever you need there. As long as you preserve the coverage, I can't care less about what tools we use to test the system.

**Comment by paulo-ferraz-oliveira** [comment]
I'm going to dig deeper, since it seems `katana` needs a bit of an update too.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/inaka/erlang-katana/pull/160 opened, after which I think I'll tackle this. Let me prepare it with a `_checkouts` -oriented approach, though.
