### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/apns4erl#239]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by ferigis** [comment]
that would be great. @elbrujohalcon do you know if we can move to GH actions? I am using them in private projects but you know more about the Inaka status in GH and if that would generate a cost

**Comment by elbrujohalcon** [comment]
We totally can, @ferigis
