### ISSUE TITLE
CRASH gun_http2:parse in server logs

### ISSUE THREAD

**Issue by jainygaurav** [inaka/apns4erl#242]
> OTP: 19.3.6
> apns4erl: from master
> 

* I have ejabberd running on aws EC2 instance.
* I have an ejabberd module
* I do the following inside ejabberd module `my_apns_module.erl` which is running as a gen_server started by ejabberd:

```
init([Host, _Opts]) ->
        apns:start(),
        case apns:connect(cert, ?APNS_CONNECTION) of
             {ok, ServerPid} -> ?ERROR_MSG("apns connection successful with PID ~p~n", [ServerPid]);
             {error, timeout} -> ?ERROR_MSG("apns connection unsuccessful reason timed out", [])
        end,
```

* I am able to send push notifications with the code above.
* But after few days, I observe the following in ejabberd logs
* And then I can not send push notifications until I restart ejabberd
* Then after few days, it happens again.

> CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: no function clause matching gun_http2:parse(<<>>, close) line 77

Please help me resolve this issue.

**Comment by jainygaurav** [comment]
OTP: 19.3.6
apns4erl: from master

Can you please help me with this issue:

Last push notification sent:

2021-03-02 21:27:36.030 [error] <0.506.0>@my_mod_apns:sendAPNS:290 Success in request. Reason was: 200 with <<"c2ca5csdsc5b0550a74fe799asda96d9049d3502c58fd5e4b27e98ed1b97e49c2d">>

Then after couple of days:

2021-03-05 15:51:38.055 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours crashed with reason: no function clause matching gun_http2:parse(<<>>, close) line 77
2021-03-05 15:51:38.056 [error] <0.517.0> Supervisor gun_sup had child gun started with {gun,start_link,undefined} at <0.530.0> exit with reason function_clause in context child_terminated

**Comment by jainygaurav** [comment]
I found this doing some research if it helps:

https://github.com/ninenines/gun/issues/105

**Comment by jainygaurav** [comment]
Actually, since I do apns:connect inside spawn as suggested by: https://stackoverflow.com/questions/66464616/how-can-i-receive-messages-sent-to-a-pid-which-running-inside-a-gen-server

This error is happening much more frequently:

> 2021-03-05 20:31:07.694 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours crashed with reason: no function clause matching gun_http2:parse(<<>>, close) line 77
> 2021-03-05 20:31:07.694 [error] <0.536.0> Supervisor gun_sup had child gun started with {gun,start_link,undefined} at <0.543.0> exit with reason function_clause in context child_terminated
> 2021-03-05 20:48:28.116 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 0 neighbours crashed with reason: no function clause matching gun_http2:parse(<<>>, close) line 77
> 2021-03-05 20:48:28.117 [error] <0.536.0> Supervisor gun_sup had child gun started with {gun,start_link,undefined} at <0.561.0> exit with reason function_clause in context child_terminated
> 2021-03-05 21:28:51.641 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours crashed with reason: no function clause matching gun_http2:parse(<<>>, close) line 77
> 2021-03-05 21:28:51.641 [error] <0.536.0> Supervisor gun_sup had child gun started with {gun,start_link,undefined} at <0.590.0> exit with reason function_clause in context child_terminated
>

**Comment by paulo-ferraz-oliveira** [comment]
@jainygaurav, did you try getting help next to the `gun` folks? I'm not sure (without digging further) that issue comes from `apns4erl`.

**Comment by jainygaurav** [comment]
OK..let me try asking on https://github.com/ninenines/gun/issues

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira as per your comment on https://github.com/ninenines/gun/issues/261, can you please point me to build or code changes w.r.t gun-2.0.0-rc1 that I need to do to get it working on my end.

**Comment by paulo-ferraz-oliveira** [comment]
Specifically for `apns4erl` I can't, because I haven't done it yet (so haven't gone through the upgrade pains), but as a general replacement you could try to add `{gun, "2.0.0-rc.1"}` to your `rebar.config` to lock that version (you might want to do `rebar3 upgrade` at this point). The only change I had to do, in another context (not `apns4erl`) was rename `transport_opts` as `tls_opts`, which I guess will have to be done in `apns4erl` some time in the future, too.

**Comment by jainygaurav** [comment]
let me try...

**Comment by jainygaurav** [comment]
```
./rebar3 upgrade
===> Verifying dependencies...
===> Fetching base64url v1.0.1
===> Fetching gun v2.0.0-rc.1
===> Fetching jsx v3.0.0
===> Fetching cowlib v2.10.1
===> No upgrade needed for base64url
===> No upgrade needed for gun
===> No upgrade needed for jsx
===> No upgrade needed for cowlib
./rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling cowlib
===> Compiling base64url
===> Compiling gun
_build/default/lib/gun/src/gun_socks.erl:131: Warning: a term is constructed, but never used
_build/default/lib/gun/src/gun_socks.erl:136: Warning: a term is constructed, but never used

===> Compiling jsx
===> Analyzing applications...
===> Compiling apns

```

**Comment by paulo-ferraz-oliveira** [comment]
@jainygaurav, you don't need to double post here and in `gun`. 😄

That warning's supposed to be innocent, but you'll probably run into trouble when using `apns4erl` because of the `tls_opts` as I mentioned before (unless you're not doing TLS). You might need to do a fork and experiment with that.

**Comment by jainygaurav** [comment]
ok...

**Comment by paulo-ferraz-oliveira** [comment]
You can also add this repo. to your watchlist and when the next version is out just import it.

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira Just FYI...**without** changing `transport_opts` -> `tls_opts`:

I get the following output:

> erl -pa _build/default/lib/*/ebin/ -config test/test.config
> Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
> 
> Eshell V8.3.5  (abort with ^G)
> 1> apns:start().
> ok
> 2> apns:connect(cert, my_first_connection).
> {ok,<0.87.0>}
> 3> 
> =ERROR REPORT==== 7-Mar-2021::23:11:52 ===
> ** State machine my_first_connection terminating
> ** Last event = {internal,{"api.development.push.apple.com",443,
>                            #{protocols => [http2],
>                              retry => 0,
>                              transport_opts =>
>                                  [{certfile,"priv/apns-dev-cert.pem"},
>                                   {keyfile,"priv/apns-dev-key-noenc.pem"}]}}}
> ** When server state  = {open_common,#{backoff => 1,backoff_ceiling => 10,
>                                        client => <0.58.0>,
>                                        connection =>
>                                            #{apple_host =>
>                                                  "api.development.push.apple.com",
>                                              apple_port => 443,
>                                              certfile =>
>                                                  "priv/apns-dev-cert.pem",
>                                              keyfile =>
>                                                  "priv/apns-dev-key-noenc.pem",
>                                              name => my_first_connection,
>                                              timeout => 10000,type => cert}}}
> ** Reason for termination = error:{badmatch,
>                                    {error,
>                                     {options,
>                                      {transport_opts,
>                                       [{certfile,"priv/apns-dev-cert.pem"},
>                                        {keyfile,
>                                         "priv/apns-dev-key-noenc.pem"}]}}}}
> ** Callback mode = state_functions
> ** Stacktrace =
> **  [{apns_connection,open_common,3,
>                       [{file,"/home/ubuntu/tmpXYZ/apns4erl/src/apns_connection.erl"},
>                        {line,254}]},
>      {gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1223}]},
>      {gen_statem,loop_event,6,[{file,"gen_statem.erl"},{line,995}]},
>      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
> 

Then I did the changes like this:

git diff src/apns_connection.erl
@@ -231,7 +231,7 @@ open_origin(internal, _, #{connection := Connection} = StateData) ->
     {next_event, internal, { Host
                            , Port
                            , #{ protocols      => [http2]
-                              , transport_opts => TransportOpts
+                              , tls_opts => TransportOpts
                               , retry          => 0
                               }}}}.
 
Then my output was as follows:

erl -pa _build/default/lib/*/ebin/ -config test/test.config
Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3.5  (abort with ^G)
1> apns:start().
ok
2> apns:connect(cert, my_first_connection).
{ok,<0.87.0>}
3> 

I assume this is what you meant to get it working for this `gun` dependency.

```
{deps, [
  {gun, "2.0.0-rc.1"},
  {jsx, "3.0.0"},
  {base64url, "1.0.1"}
]}.

```

**Comment by paulo-ferraz-oliveira** [comment]
Yes, that's it. So the only change was that one? Nice.

Now, just let it run and check if the same thing that was happening before still happens. If it does, it requires further digging around.

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira Thank you so much for being awesome!

I will update accordingly.

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira When I try to send push notification, I get this error:

> ** Reason for termination = error:{'function not exported',
>                                       {string,lowercase,1}}

```
2> apns:start().ok
3> {ok, Pid} = apns:connect(cert, my_first_connection).
{ok,<0.89.0>}
4> DeviceId = <<"4c1f88da4e9c5ca23a6d186dad745b3b6817d9fd2ddea095fbfa667c0929d31d">>.
<<"4c1f88da4e9c5ca23a6d186dad745b3b6817d9fd2ddea095fbfa667c0929d31d">>
5> Notification = #{aps => #{alert => <<"you have a message">>}}.
#{aps => #{alert => <<"you have a message">>}}
6> apns:push_notification(my_first_connection, DeviceId, Notification).

=ERROR REPORT==== 8-Mar-2021::03:28:04 ===
** State machine my_first_connection terminating
** Last event = {{call,{<0.60.0>,#Ref<0.0.1.268>}},
                 {push_notification,<<"4c1f88da4e9c5ca23a6d186dad745b3b6817d9fd2ddea095fbfa667c0929d31d">>,
                                    <<"{\"aps\":{\"alert\":\"you have a message\"}}">>,
                                    #{apns_expiration => <<"0">>,
                                      apns_priority => <<"10">>,
                                      apns_push_type => <<"alert">>,
                                      apns_topic => <<"com.example.myapp">>}}}
** When server state  = {connected,#{backoff => 1,backoff_ceiling => 10,
                                     client => <0.60.0>,
                                     connection =>
                                         #{apple_host =>
                                               "api.development.push.apple.com",
                                           apple_port => 443,
                                           certfile =>
                                               "/etc/ejabberd/certs/apns-dev-cert.pem",
                                           keyfile =>
                                               "/etc/ejabberd/certs/apns-dev-key-noenc.pem",
                                           name => my_first_connection,
                                           timeout => 10000,type => cert},
                                     gun_monitor => #Ref<0.0.1.190>,
                                     gun_pid => <0.91.0>}}
** Reason for termination = error:{'function not exported',
                                      {string,lowercase,1}}
** Callback mode = state_functions
** Stacktrace =
**  [{gun,normalize_headers,1,
          [{file,"/home/ubuntu/tyme-it-backend/apns4erl_v2_otp_19.3.6/_build/default/lib/gun/src/gun.erl"},
           {line,654}]},
     {gun,request,6,
          [{file,"/home/ubuntu/tyme-it-backend/apns4erl_v2_otp_19.3.6/_build/default/lib/gun/src/gun.erl"},
           {line,638}]},
     {apns_connection,push,5,
                      [{file,"/home/ubuntu/tyme-it-backend/apns4erl_v2_otp_19.3.6/src/apns_connection.erl"},
                       {line,475}]},
     {apns_connection,connected,3,
                      [{file,"/home/ubuntu/tyme-it-backend/apns4erl_v2_otp_19.3.6/src/apns_connection.erl"},
                       {line,312}]},
     {gen_statem,call_state_function,5,[{file,"gen_statem.erl"},{line,1223}]},
     {gen_statem,loop_event,6,[{file,"gen_statem.erl"},{line,995}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
** exception exit: {undef,{gen_statem,call,
                                      [my_first_connection,
                                       {push_notification,<<"4c1f88da4e9c5ca87a6d186dad745b3b6817d9fd2ddea095fbfa608c0929d31d">>,
                                                          <<"{\"aps\":{\"alert\":\"you have a message\"}}">>,
                                                          #{apns_expiration => <<"0">>,apns_priority => <<"10">>,
                                                            apns_push_type => <<"alert">>,
                                                            apns_topic => <<"com.example.myapp">>}},
                                       infinity]}}
     in function  gen:do_call/4 (gen.erl, line 177)
     in call from gen_statem:call/3 (gen_statem.erl, line 449)


```

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira https://github.com/erlang/otp/issues/4595

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira Would you have any idea on https://github.com/ninenines/gun/issues/263?

**Comment by paulo-ferraz-oliveira** [comment]
According to what @essen replied, there should be no problem. Is it because you're logging/tracing stuff and see the messages? What leads you to believe there is an issue?

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira I was just looking to make it work like gun-1.3.3. I replied there.

**Comment by paulo-ferraz-oliveira** [comment]
Sure, but the intent (I guess) should be to "make it work", not "make it work like before" :-)

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira There were multiple reasons for me to make it work like gun-1.3.3.

* This issue (#242) was happening when `apns4erl` was not disconnecting and reconnecting at 2 hours interval. So, to make it potentially re-producible in `gun-2.0.0-rc.1`, I had to make `gun-2.0.0-rc.1` work like `gun-1.3.3`.

* Then I read https://github.com/inaka/apns4erl ---> **Close Connections** ---> **Best Practices for Managing Connections**. So, I assumed `apns4erl` does not want frequent close connections and was relying on the default gun-1.3.3 ping behavior to keep connections alive.

* But since I, and not `apns4erl`, upgraded gun ---> 2.0.0-rc.1, so I wanted to remain consistent with `apns4erl` behavior with `1.3.3`. 

* I assumed when `apns4erl` will officially migrate to `gun-2.0.0,` they will/should do what I did to remain consistent with prior beahvior.

* Lastly, having done many trials and errors and having limited understanding of various things, I was not sure whether I did something wrong or whether it was the expected behavior for `gun-2.0.0-rc.1 `as the behavior deviated from `gun-1.3.3`

* So, to make myself clear and be sure, I just wanted to make `gun-2.0.0-rc.1`  work like `gun-1.3.3`

**Comment by paulo-ferraz-oliveira** [comment]
> I assumed when apns4erl will officially migrate to gun-2.0.0, they will/should do what I did to remain consistent with prior behavior.

I invite you to open a pull request (in `apns4erl`) with the required changes, so when the time comes it would just be closer to updating the `rebar.config` pointer. What do you say? 😄 

As per what I said in my last comment, if our goal is to keep current behaviour we should respect current requirements (having in mind that `gun` might not allow us to do that, I'm not sure). I'd prefer to not break anything for the consumer of the `apns4erl` API just by updating `gun`, but it might warrant some extra care that we should be verbose in stating in the release notes.

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira I have never done a pull request or contributed to external projects. I will learn how to do it and will do the same.

Thank you again for everything.

**Comment by paulo-ferraz-oliveira** [comment]
It's fairly easy.

I'll give you an example for `apns4erl`.

1. you fork the project (there's a Fork button at the top),
2. you clone locally and do your stuff in a branch called (e.g.) `feature/gun-2.0.0`,
3. you push locally and refresh the page: there should now be a button letting you know a pull request can be open.

And that's it!

**Comment by jainygaurav** [comment]
Great...It will be a good first experience.

**Comment by jainygaurav** [comment]
Looks like this issue is fixed with `gun-2.0.0-rc.1`. I sent last push notification on `Mar 10` and kept the connection alive as with `gun-1.3.3` (#245) before sending a push notification again on `Mar 14` without a server restart. Push notification from `Mar 14` went thru **successfully**.

```
2021-03-10 20:26:39.495 [error] <0.497.0>@mod_tymeit_apns:sendAPNS:320 Success in request. Reason was: 200 with <<"4c1f88da4e9c5ca87a6d186dad745b3b6817d9fd2ddea095fbfa608c0929d31d">>
2021-03-14 21:10:46.781 [error] <0.497.0>@mod_tymeit_apns:sendAPNS:320 Success in request. Reason was: 200 with <<"9e3d4650671f1c0557dfe751f6019b2ad0ec9d6afe5b822fb1d5a6a07fa22b4d">>
2021-03-14 21:15:03.368 [error] <0.497.0>@mod_tymeit_apns:sendAPNS:320 Success in request. Reason was: 200 with <<"022bc5aba4ed7aa9e964d3c47225c4528ba5dd1e82113bb08af255b5f1bad3b4">>
```

I will complete the pull request by EOW, Mar 19.

Thank you so much for helping me out with this issue.

**Comment by paulo-ferraz-oliveira** [comment]
> I will complete the pull request by EOW, Mar 19.

Cool. 👍

**Comment by jainygaurav** [comment]
@paulo-ferraz-oliveira https://github.com/inaka/apns4erl/pull/246.

Please let me know if anything else needs to be done.
