### ISSUE TITLE
Erlang (Not apns4erl) Question

### ISSUE THREAD

**Issue by jainygaurav** [inaka/apns4erl#244]
Is it possible you can answer an erlang question for me:

https://stackoverflow.com/questions/66464616/how-can-i-receive-messages-sent-to-a-pid-which-running-inside-a-gen-server

**Comment by paulo-ferraz-oliveira** [comment]
@jainygaurav, Erlang has a Slack, at https://erlanger.slack.com/. You should join as it might help you with some questions.

**Comment by paulo-ferraz-oliveira** [comment]
In the case of your questions, at the same time, I might suggest you read https://erlang.org/doc/man/gen_server.html. If doubts persist we could discuss in Slack (e.g. #general) or you can pull request to fix what you think can be improved.

**Comment by jainygaurav** [comment]
ok.
