### ISSUE TITLE
Support latest APNs notification format

### ISSUE THREAD

**Issue by dcheckoway** [inaka/apns4erl#30]
Currently apns4erl supports the "Enhanced Notification Format" (command=1), which is now legacy:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW1

The latest notification format (command=2) is frame-based.  Any plans to support this soon?

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW1

**Comment by ferigis** [comment]
we can close that ticket
