### ISSUE TITLE
How can I get apns4erl integrated with ejabberd

### ISSUE THREAD

**Issue by monkeyfdude** [inaka/apns4erl#45]
I am new to erlang and ejabberd. I have gone through docs and tutorials on erlang and ejabberd.

I am still not sure how to integrate apns4erl with ejabberd. I need to be able to do the following:

* Add apns4erl module to with ejabberd_hooks for event offline_message_hook
* That should start the apns4erl module.
* From there, every a offline message is received, I need to be able to call send_message from apns4erl.
* Also, I need have an persistent connection from apns4erl to Apple APN server.

Would you be able to give me starting pointers on to get apns4erl started with ejabberd??

Do I need to start apns4erl application from my custom module that I will hook with ejabberd. is that how it will work??

Thanks in advance!
Gaurav Jain

**Comment by manuel-rubio** [comment]
Yes, you can do it as you define. Create the hook for offline with the highest priority (and the lowest number to be sure is running before mod_offline) and send the push notification.

You'll also need a mechanism to register the tokens and retrieve them, and in the start of the module you can configure the connection getting the configuration params from the configuration of the module.

Remember to add the dependency in the rebar.config or rebar.config.script (depends if you want to use mongooseim or ejabberd).

Pretty easy :-)

**Comment by monkeyfdude** [comment]
Thank you for your response. Right now, I am trying to figure out how to write the hook.

When I was looking at the code for apns4erl, it requires sys.config. Would you know where would I plug that in Ejabberd framework.

Also, please shed some more light on rebar.config part. What is that??

Thanks again

**Comment by manuel-rubio** [comment]
No, is not needed to use sys.config, you can use the connect with all the params and get the params from the module configuration using `gen_mod:get_module_opt/4` function.

**Comment by monkeyfdude** [comment]
Thanks you...let me try...I will post updates...

**Comment by elbrujohalcon** [comment]
@monkeyfdude when you figure it out, feel free to add a wiki page describing the process if you feel like it :)

**Comment by monkeyfdude** [comment]
I would definitely do it...I think I should be able to figure out soon....of course with some expert help.....anyways thanks a lot for apns4perl....it makes life easy for certain people

**Comment by monkeyfdude** [comment]
I think I am able to connect using pans:connect. How can I check if its a persistent connection.

Would it show up in netstat -ln....is there a timeout of inactivity on these connections??

I did get this in server logs:

<0.380.0> Feedback server disconnected. Waiting 18000000 millis to connect again...

**Comment by monkeyfdude** [comment]
I get this error in ejabberd logs

 gen_server 'test-connection' terminated with reason: {'module could not be loaded',[{jiffy,encode,[{[{<<"aps">>,{[{<<"sound">>,<<"chime">>}

Please provide pointers!

**Comment by monkeyfdude** [comment]
I can successful send push notifications to my device using apns4erl...closing resolved.

I may have other reliability related questions that I will ask in separate tickets

Thank you all for your help and support....no words can express it!!!!
