### ISSUE TITLE
How to get .pem file for Apple APNS

### ISSUE THREAD

**Issue by monkeyfdude** [inaka/apns4erl#46]
In the readme.md, following is mentioned:

NOTE 2: To generate the .pem file, from the .cer an .p12 files provided by Apple, you can use this "https://github.com/inaka/apns4erl/blob/master/inaka/apns4erl/blob/master/priv/test_certs"

Why is this step needed? Should not we get .pem files from Apple itself?

Could you please elaborate on this step?

**Comment by elbrujohalcon** [comment]
I know not much about Apple, but sometimes the iOS devs gave me just .cer and .p12 files… if that's not your case, awesome… you don't need that step.
