### ISSUE TITLE
SSL: Socket error: etimedout

### ISSUE THREAD

**Issue by monkeyfdude** [inaka/apns4erl#52]
I got following in my logs. It is coming from apns4erl.

2015-04-29 00:01:59.992 [info] <0.3157.0> SSL: Socket error: etimedout 
2015-04-29 00:01:59.992 [info] <0.395.0> APNS disconnected

Till this point I lost all my messages needed to be sent via apns.

After this, when I send another message:

I got following:
2015-04-29 00:03:03.134 [info] <0.395.0> Reconnecting to APNS...

Then I was able to send apns messages.

Would you know what could cause the disconnect?

Can I set any configuration to timeout faster to minimize loss of messages?

Should I disconnect and reconnect everytime I send a message?

**Comment by manuel-rubio** [comment]
Yes, maybe your router is dropping connections that has not been used for long time. I configure in my fork the auto-reconnection if the SSL socket was inactive for more than 5 minutes, but if your router is configured for drop TCP connections before than 5 minutes, then you have that problem.

You should configure it using the `expires_conn` parameter. See the `Readme.md` file for further information.

**Comment by monkeyfdude** [comment]
I dont see anything related to ```expires_conn``` in Readme.md in my repo. I did do a git pull.

Could you please please provide the URL to it?

**Comment by manuel-rubio** [comment]
https://github.com/altenwald/apns4erl review the `queue` branch.

**Comment by mdaguete** [comment]
+1 to add @manuel-rubio patch to upstream, please @elbrujohalcon

**Comment by elbrujohalcon** [comment]
@mdaguete @manuel-rubio of course, just send a PR, please

**Comment by mdaguete** [comment]
Hello,

I've extracted @manuel-rubio's code to my own branch

https://github.com/mdaguete/apns4erl/tree/inactivity_timeout

I'm going to test it and if no error appears I'll submit a PR.

Thanks.

**Comment by elbrujohalcon** [comment]
merged
