### ISSUE TITLE
Build error on R16B03-01 and R15B03

### ISSUE THREAD

**Issue by pnc** [inaka/apns4erl#59]
Thanks for the great library! We've been running it in production for three or four years with great success.

It looks like the change (https://github.com/inaka/apns4erl/commit/bd9048e265eb7804ed59982431a741bc593657da) to use `queue:queue()` as a type rather than plain `queue()` might have broken the build on releases older than R17:

```
ERLC   apns.erl apns_queue.erl apns_sup.erl apns_connection.erl
src/apns_queue.erl:32: referring to built-in type queue as a remote type; please take out the module name
src/apns_queue.erl:111: referring to built-in type queue as a remote type; please take out the module name
make: *** [ebin/apns.app] Error 1
```

It looks like the OTP team knew this would be a backwards-incompatible change and introduced a compiler option to suppress the warning, which might be more appropriate than switching to the new type (at least until R18 is released): http://erlang.org/pipermail/erlang-questions/2014-March/078081.html

If support for older releases (R14, 15, and 16, as defined in the `rebar.config`) is still desired, is it possible to use a preprocessor guard around the new types? We don't use types in our Erlang app, so I'm unsure here.

Here are the build results from three OTP versions: https://travis-ci.org/eleostech/apns4erl/builds/67406167

**Comment by ferigis** [comment]
currently we only support 19+. We can close that ticket
