### ISSUE TITLE
Is there known issues with Erlang 18 ?

### ISSUE THREAD

**Issue by sylane** [inaka/apns4erl#60]
Rebar config specify version 17 as maximum version number, is there known issues with Erlang 18 ?

**Comment by elbrujohalcon** [comment]
The app was never tested on R18.
And we're not planning to test it anytime soon.
If you try it on R18 and it works, please submit a PR with the change and I'll gladly merge it :)

**Comment by igaray** [comment]
There are currently some calls in `apns.erl` to deprecated BIFS, which will produce compilation errors.
Also, one of the dependencies (eper) is currently not Erlang 18 compatible. 
I would vote to remove sync and eper as dependencies as they are only development dependencies.

**Comment by elbrujohalcon** [comment]
@igaray yeah… We should remove those

**Comment by lsxredrain** [comment]
otp 18.1 is fail when i build  eper

**Comment by ferigis** [comment]
our current version only supports 19+
