### ISSUE TITLE
APNS return invalid_token, but the token is ok!

### ISSUE THREAD

**Issue by shuimutiane** [inaka/apns4erl#66]
I've a problem because I send messages in broadcast to several devices, apns return invalid_token for me every few seconds, I resend the msg for this invalid_token is ok, this means the returned invalid_token is ok. Why apns return invalid_token  every few seconds?

**Comment by elbrujohalcon** [comment]
That would be very difficult to diagnose from this side, @shuimutiane … `invalid_token` comes straight from APNS

**Comment by shuimutiane** [comment]
It took me 15 minutes to send messages in broadcast to 100000 devices，apns returned a invalid_token for me every few seconds, and returned 32 invalid_tokens in all, I resend the msg for these invalid_tokens is ok. Why apns returned invalid_token which is not invalid for me?

**Comment by shuimutiane** [comment]
It took me 15 minutes to send messages in broadcast to 100000 devices，apns returned a invalid_token for me every few seconds, and returned 32 invalid_tokens in all, I resend the msg for these invalid_tokens is ok. Why apns returned invalid_token which is not invalid for me?
Thank you for your help！

**Comment by elbrujohalcon** [comment]
@shuimutiane it might be an APNS issue, have you tried contacting Apple about this?

**Comment by ferigis** [comment]
I think we can close this issue for now. It seems to be out of the apns4erl scope.
