### ISSUE TITLE
Can't use multiple certificates

### ISSUE THREAD

**Issue by comtihon** [inaka/apns4erl#70]
Hi! I have no problem using one certificates, just specifying it in sys.conf and everything works.
But I want to have different connections with different certificates, so I have to use this sample:

```
Connection = #apns_connection{cert_file=undefined,
                              cert=CertDER,
                              key={'RSAPrivateKey', KeyDER}},
apns:connect(Connection).
```

The problem is, that I got errors:

```
{badmatch,{error,{{badarg,[{ets,select_delete,[undefined,[{{{undefined,'_','_'},'_'},[],[true]}]],[]},{ets,match_delete,2,[{file,"ets.erl"},{line,700}]},{ssl_pkix_db,remove_certs,2,[{file,"ssl_pkix_db.erl"},{line,243}]},{ssl_connection,terminate,3,[{file,"ssl_connection.erl"},{line,935}]},{tls_connection,terminate,3,[{file,"tls_connection.erl"},{line,335}]},{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,610}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},{gen_fsm,sync_send_all_state_event,[<0.461.0>,{start,30000},infinity]}}}}
```

apns app is started.
I made a guess, that my sertificates are encrypted - but `public_key:pem_decode(CertBin)` returns `[]` on both key and cert files.
What should I do to make it working?

**Comment by jfacorro** [comment]
@comtihon How are you getting the values for `CertDER` and `KeyDER`?

**Comment by comtihon** [comment]
@jfacorro I read token through `file:read_file:1`and save it to mongo. I checked - files are the same, which was read from file and from database.

**Comment by comtihon** [comment]
I found out, that error rises during ssl:connect, in ssl_pkix_db,remove_certs,2
It takes place in your driver and in my own immplementation, too. I think, that I do something wrong with my certificates.

**Comment by ferigis** [comment]
I think we can close that one due the problem was related with the certificates
