### ISSUE TITLE
loss of network connectivity crashes the app

### ISSUE THREAD

**Issue by bdionne** [inaka/apns4erl#80]
if the network is lost after apns is started, .eg. `{error, nxdomain}`, the app crashes. What happens is when the feedback timeout occurs, a reconnect message is sent, which fails, crashing the `gen_server`. The `simple_one_for_one` strategy with `transient` workers is quickly exhausted, crashing the supervisor and eventually the app.

**Comment by ferigis** [comment]
Current apns4erl has an exponential backoff strategy in order to reconnect when connection is lost.
