### ISSUE TITLE
ssl:connect return {error,closed}

### ISSUE THREAD

**Issue by sunfaces** [inaka/apns4erl#82]
Hi,I've encountered a problem as the title describes

The Erlang version is R17.5,but the ssl version is 7.0(because ssl6.0 caused error})

**Comment by sunfaces** [comment]
I'v tried R15B02, R17.5,R18.0,all returned {error,closed}
The operation steps are:
    1.erl -pa ./ebin
    2.ssl:connect("gateway.sandbox.push.apple.com",2195,[{mode,binary},{keyfile,"/apns4erl/priv/key.pem"},{certfile,"/apns4erl/priv/cert.pem"},{password,"asdf"},{versions,['tlsv1.1']}],100000).
     3.tried option tlsv1.2  tlsv1 ssl3

**Comment by zhongwencool** [comment]
```
openssl x509 -in ./priv/apns_production.pem -noout -text
```

check if your app pem is ok.

apple think this connection is not ok, so it's return {error, closed} .

**Comment by sunfaces** [comment]
thanks,man,problem resolved
