### ISSUE TITLE
Full Library Revamp

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/apns4erl#84]
We need to get this library into Erlang/OTP 18.x world.
The plan is to start using maps where we used records before, stop requiring headers, revisit the way we start/stop connections and how we properly display errors from APNS.
In the process, we should address as many open issues as possible and ensure 100% code coverage in tests.

**Comment by ferigis** [comment]
@elbrujohalcon I think we can close that one, right?

**Comment by elbrujohalcon** [comment]
@ferigis aw yeah!!
