### ISSUE TITLE
One of dependencies (inaka/sync) now unavailable

### ISSUE THREAD

**Issue by bosky101** [inaka/apns4erl#89]
the rebar.config mentions https://github.com/inaka/sync.git

but that repo does not exist anymore

**Comment by elbrujohalcon** [comment]
Would you mind sending a PR replacing that link by the following or just removing it from the list if you prefer?
```erlang
{sync, ".*",   {git, "https://github.com/rustyio/sync.git", "9c78e7b"}} 
```
